version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "8000:8000"
            - "5173:5173"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        environment:
            APP_ENV: local
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: paciente
            DB_USERNAME: root
            DB_PASSWORD:

            VITE_APP_URL: http://localhost:8000
            VITE_HOST: localhost
            VITE_PORT: 5173

    mysql:
        image: mysql:8.0
        container_name: paciente_mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: paciente

        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "root",
                    "-p",
                ]

            timeout: 20s
            retries: 3

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma_paciente
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_USER: root

        depends_on:
            - mysql

volumes:
    mysql_data:
