services:
    mysql:
        image: mysql:8.0
        container_name: mysql_laravel
        environment:
            # MYSQL_ROOT_PASSWORD:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: inventario
            # MYSQL_USER: root
            # MYSQL_PASSWORD:
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "root",
                    "-p${MYSQL_ROOT_PASSWORD}",
                ]
            timeout: 20s
            retries: 3
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma_laravel
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql # El nombre del servicio de MySQL en docker-compose
            PMA_USER: root
            #PMA_PASSWORD: tu_password_root # Debe coincidir con la contraseña de root de MySQL
        depends_on:
            - mysql

volumes:
    mysql_data:
